##post ----------------------------------------------------------------------------

###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?sender=674389a7c0680592b6760b57

###

GET http://localhost:3000/post/67438271de1accd931a9171a

###
POST http://localhost:3000/post
Content-Type: application/json

{
    "sender": "674389a7c0680592b6760b57",
    "title": "Post 3",
    "content": "This is post 2"
}

###
PUT http://localhost:3000/post/67437e0bd971209be952c7da
Content-Type: application/json

{
    "sender": "674389a7c0680592b6760b57",
    "title": "Post 5",
    "content": "This is post 300"
}


##comment ----------------------------------------------------------------------------

###

GET http://localhost:3000/comment

###

GET http://localhost:3000/comment/67438d47ef31dc2a80b19cfd
###

GET http://localhost:3000/comment?postId=67442097c150df7d32594b57

###
POST http://localhost:3000/comment
Content-Type: application/json

{
    "message": "This is comment 2",
    "post": "67442097c150df7d32594b57",
    "user": "674389a7c0680592b6760b57"
}

###

PUT http://localhost:3000/comment/67439b04b236759199524f0f
Content-Type: application/json

{
    "message": "This is an updated comment agian",
    "post": "6734d9ef7deba0e935a8a5f1",
    "user": "674389a7c0680592b6760b57"
}

###

DELETE http://localhost:3000/comment/67437e0bd971209be952c7da
